Shop/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

from django.conf import settings
from django.conf.urls.static import static

from shop.views import info, contacts, feedback
urlpatterns = [
    path('admin/', admin.site.urls),
    path('info/', info),
    path('contacts/', contacts),
    path('feedback/', feedback),
    # url(r'^info/', include(('shop.urls', 'info'), namespace='info')),
    url(r'^cart/', include(('cart.urls', 'cart'), namespace='cart')),
    url(r'^orders/', include(('orders.urls', 'orders'), namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
    url(r'^', include(('shop.urls', 'shop'), namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.cart_detail, name='cart_detail'),
    url(r'^add/(?P<product_id>\d+)/$', views.cart_add, name='cart_add'),
    url(r'^remove/(?P<product_id>\d+)/$', views.cart_remove, name='cart_remove'),
]

orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^create/$', views.order_create, name='order_create'),
]

shop/urls.py
from django.urls import path
from . import views
from django.conf.urls import include, url

urlpatterns = [
    url(r'^$', views.product_list, name='product_list'),
    url(r'^info$', views.info, name='info'),

    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="Количество")
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    Ваша корзина покупок.
{% endblock %}
{% block content %}
    <h1>Ваша корзина покупок</h1>
    <table class="cart">
        <thead>
        <tr>
            <th>Картинка</th>
            <th>Товар</th>
            <th>Количество</th>
            <th>Удалить</th>
            <th>Стоимость</th>
            <th>Итог</th>
        </tr>
        </thead>
        <tbody>
        {% for item in cart %}
            {% with product=item.product %}
                <tr>
                    <td>
                        <a href="{{ product.get_absolute_url }}">
                            <img src="
                                {% if product.image %}
                                    {{ product.image.url }}
                                {% else %}
                                    {% static "img/no_image.png" %}
                                {% endif %}">
                        </a>
                    </td>
                    <td>{{ product.name }}</td>
                    <td>{{ item.quantity }}</td>
                    <td><a href="{% url "cart:cart_remove" product.id %}">Удалить</a></td>
                    <td class="num">{{ item.price }}руб.</td>
                    <td class="num">{{ item.total_price }}руб.</td>
                </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Итого</td>
            <td colspan="4"></td>
            <td class="num">{{ cart.get_total_price }}руб.</td>
        </tr>
        </tbody>
    </table>
    <p class="text-right">
        <a href="{% url "shop:product_list" %}" class="button light">Продолжить покупки</a>
        <a href="{% url "orders:order_create" %}" class="button">
            Оформить заказ
        </a>
    </p>
{% endblock %}